sudo: required
services:
  - docker

before_install:
  - docker build -t aniketrangnekar/docker-react -f Dockerfile.dev .

script:
  - docker run aniketrangnekar/docker-react npm run test -- --coverage